mod test

diff --git a/.github/workflows/actions_test.yaml b/.github/workflows/actions_test.yaml
--- a/.github/workflows/actions_test.yaml
+++ b/.github/workflows/actions_test.yaml
@@ -35,7 +35,7 @@ jobs:
             source /opt/ros/melodic/setup.bash && \
             sudo touch /dev/rt{buzzer,motor,motoren,motor_raw_{l,r}}0 && \
             sudo chmod 666 /dev/rt{buzzer,motor,motoren,motor_raw_{l,r}}0 && \
-            echo "0 0 0 0" | sudo tee /dev/rtlightsensor0 && \
+            echo "0 0 0 0" | sudo touch /dev/rtlightsensor0 && \
             sudo chmod 666 /dev/rtlightsensor0 && \
             echo "0" | sudo tee /dev/rtswitch{0,1,2} && \
             sudo chmod 666 /dev/rtswitch{0,1,2}
@@ -45,6 +45,8 @@ jobs:
           docker exec ros_ci_container bash -c "
             source /opt/ros/melodic/setup.bash && \
             source /root/catkin_ws/devel/setup.bash && \
+            ls -l /dev/rtlightsensor0 || echo 'no file' && \
+            cat /dev/rtlightsensor0 || echo 'cannot read' && \
             xvfb-run -a rostest pimouse_2025 test.launch
           "
 
